version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: todo-container 
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: todo-db 
      MYSQL_USER: admin 
      MYSQL_PASSWORD: admin 
    ports:
      - "3306:3306"

